---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Define php_config_file.
  set_fact:
    php_config_file: "{{ __php_config_file }}"
  when: php_config_file is not defined

- name: Define zabbix_packages.
  set_fact:
    zabbix_packages: "{{ __zabbix_packages | list }}"
  when: zabbix_packages is not defined

# Setup/install tasks..
- include_tasks: "setup-{{ ansible_os_family }}.yml"